server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:./data/ecommerce.db
    driver-class-name: org.sqlite.JDBC
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.community.dialect.SQLiteDialect

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
