server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:./data/ecommerce.db?foreign_keys=true
    driver-class-name: org.sqlite.JDBC
    
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.dialect: org.hibernate.community.dialect.SQLiteDialect
      hibernate.hbm2ddl.import_files: import.sql
      hibernate.format_sql: true

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
